name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos:
        - windows
        - linux
        - darwin
        goarch:
        - amd64
        - arm64
        include:
        - goos: linux
          goarch: arm
          goarm: 6
        - goos: linux
          goarch: arm
          goarm: 7
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOARM: ${{ matrix.goarm }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.4

    - name: Build
      run: make dist

    - id: vars
      run: echo "distpath=$(make distpath)" >> $GITHUB_OUTPUT

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.vars.outputs.distpath }}
        path: ${{ steps.vars.outputs.distpath }}

    - run: sha256sum ${{ steps.vars.outputs.distpath }} > ${{ steps.vars.outputs.distpath }}.sha256

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.vars.outputs.distpath }}.sha256
        path: ${{ steps.vars.outputs.distpath }}.sha256

  test:
    runs-on: ubuntu-latest
    # Only runs on linux/amd64 while GitHub does not support YAML anchors.
    steps:
    - name: Test
      run: make test
